/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const Coin=(props) =>{
  const { nodes, materials } = useGLTF('/ImageToStl.com_bitcoinvox.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.imagetostl_mesh0.geometry}
        material={materials.mat0}
      />
    </group>
  )
}

useGLTF.preload('/ImageToStl.com_bitcoinvox.glb')


export default Coin;