/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Merow (https://sketchfab.com/TehMerow)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pixel-a-frame-f7a548ba0e5848c180bfaa9093e3ab71
Title: Pixel A-Frame
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const Barrier=(props) =>{
  const { nodes, materials } = useGLTF('/pixel_a-frame.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials['Material.001']}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload('/pixel_a-frame.glb')

export default Barrier;