/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Siddharth Chari (https://sketchfab.com/darthsidd1995)
License: CC-BY-NC-ND-4.0 (http://creativecommons.org/licenses/by-nc-nd/4.0/)
Source: https://sketchfab.com/3d-models/environment-relic-pixel-textured-fcfdcb113861470b91d518c998f359f0
Title: Environment Relic Pixel Textured
*/

import React, { useRef,useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

 const Earth=(props)=> {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/environment_relic_pixel_textured.glb')
  const { actions } = useAnimations(animations, group)


  useEffect(() => {
    Object.values(actions).forEach(action => action.play());
  }, [actions]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="a00ee15480b14c5092a30a73faaa0d30fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="pSphere1" position={[0, 15.295, 0]} scale={30.59}>
                  <group name="polySurface1" position={[0, -0.5, 0]} scale={1.571}>
                    <mesh
                      name="polySurface1_lambert2_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.polySurface1_lambert2_0.geometry}
                      material={materials.lambert2}
                    />
                  </group>
                  <group name="polySurface2" position={[0, -0.238, 0]} scale={1.236}>
                    <mesh
                      name="polySurface2_lambert2_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.polySurface2_lambert2_0.geometry}
                      material={materials.lambert2}
                    />
                  </group>
                </group>
                <group name="pCylinder1" position={[-27.974, 4.727, -5.781]}>
                  <mesh
                    name="pCylinder1_lambert2_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCylinder1_lambert2_0.geometry}
                    material={materials.lambert2}
                  />
                </group>
                <group name="pCylinder2" position={[15.499, 4.796, -22.329]}>
                  <mesh
                    name="pCylinder2_lambert2_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCylinder2_lambert2_0.geometry}
                    material={materials.lambert2}
                  />
                </group>
                <group name="pCylinder3" position={[30.899, 2.491, 13.925]}>
                  <mesh
                    name="pCylinder3_lambert2_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCylinder3_lambert2_0.geometry}
                    material={materials.lambert2}
                  />
                </group>
                <group
                  name="pSphere2"
                  position={[30.899, 8.091, 13.925]}
                  rotation={[0.007, -0.211, -0.724]}
                  scale={1.856}>
                  <mesh
                    name="pSphere2_lambert2_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pSphere2_lambert2_0.geometry}
                    material={materials.lambert2}
                  />
                </group>
                <group
                  name="pSphere3"
                  position={[15.499, 10.397, -22.329]}
                  rotation={[0.074, -0.175, -0.748]}
                  scale={2.141}>
                  <mesh
                    name="pSphere3_lambert2_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pSphere3_lambert2_0.geometry}
                    material={materials.lambert2}
                  />
                </group>
                <group
                  name="pSphere4"
                  position={[-27.974, 10.328, -5.781]}
                  rotation={[0.013, -0.215, -0.863]}
                  scale={1.768}>
                  <mesh
                    name="pSphere4_lambert2_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pSphere4_lambert2_0.geometry}
                    material={materials.lambert2}
                  />
                </group>
                <group name="pCylinder7" position={[-4.787, 12.421, 0]} scale={4.041}>
                  <mesh
                    name="pCylinder7_lambert2_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCylinder7_lambert2_0.geometry}
                    material={materials.lambert2}
                  />
                </group>
                <group
                  name="pCylinder8"
                  position={[0, 18.138, 0]}
                  rotation={[-Math.PI, 0.968, -Math.PI]}
                  scale={7.258}>
                  <mesh
                    name="pCylinder8_blue_strips_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCylinder8_blue_strips_0.geometry}
                    material={materials.blue_strips}
                  />
                </group>
                <group
                  name="pCylinder9"
                  position={[0, 26.365, 0]}
                  rotation={[-Math.PI, -0.917, -Math.PI]}
                  scale={7.258}>
                  <mesh
                    name="pCylinder9_blue_strips_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCylinder9_blue_strips_0.geometry}
                    material={materials.blue_strips}
                  />
                </group>
                <group
                  name="pCylinder10"
                  position={[0, 34.854, 0]}
                  rotation={[-Math.PI, 0.917, -Math.PI]}
                  scale={7.258}>
                  <mesh
                    name="pCylinder10_blue_strips_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCylinder10_blue_strips_0.geometry}
                    material={materials.blue_strips}
                  />
                </group>
                <group name="group1" position={[0, 0.656, 0]}>
                  <group name="pCylinder5" position={[13.86, 2.665, 18.519]} scale={2.547}>
                    <mesh
                      name="pCylinder5_lambert2_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.pCylinder5_lambert2_0.geometry}
                      material={materials.lambert2}
                    />
                  </group>
                  <group
                    name="pSphere5"
                    position={[13.856, 8.159, 18.518]}
                    rotation={[-Math.PI, 0.917, -Math.PI]}
                    scale={3.191}>
                    <mesh
                      name="pSphere5_lambert2_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.pSphere5_lambert2_0.geometry}
                      material={materials.lambert2}
                    />
                  </group>
                </group>
                <group name="group2" position={[0, 0.656, 0]}>
                  <group
                    name="pSphere6"
                    position={[-13.822, 8.159, 18.519]}
                    rotation={[-Math.PI, -0.917, -Math.PI]}
                    scale={3.191}>
                    <mesh
                      name="pSphere6_lambert2_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.pSphere6_lambert2_0.geometry}
                      material={materials.lambert2}
                    />
                  </group>
                  <group name="pCylinder6" position={[-13.818, 2.392, 18.519]} scale={2.547}>
                    <mesh
                      name="pCylinder6_lambert2_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.pCylinder6_lambert2_0.geometry}
                      material={materials.lambert2}
                    />
                  </group>
                </group>
                <group
                  name="pCylinder17"
                  position={[-19, 33.601, 12.847]}
                  rotation={[1.691, 0.417, 0.907]}
                  scale={1.069}>
                  <group name="polySurface15" position={[0.561, -1.309, 0]}>
                    <mesh
                      name="polySurface15_ship_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.polySurface15_ship_0.geometry}
                      material={materials.ship}
                    />
                  </group>
                  <group
                    name="polySurface16"
                    position={[0.242, -1.309, -2.909]}
                    scale={[0.971, 1, 0.979]}>
                    <mesh
                      name="polySurface16_lambert2_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.polySurface16_lambert2_0.geometry}
                      material={materials.lambert2}
                    />
                  </group>
                  <group name="polySurface17" position={[2.719, -1.309, -2.182]}>
                    <mesh
                      name="polySurface17_lambert2_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.polySurface17_lambert2_0.geometry}
                      material={materials.lambert2}
                    />
                  </group>
                  <group name="polySurface18" position={[-2.216, -1.309, -2.072]}>
                    <mesh
                      name="polySurface18_lambert2_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.polySurface18_lambert2_0.geometry}
                      material={materials.lambert2}
                    />
                  </group>
                  <group name="polySurface19" position={[0.561, -1.309, 2.681]}>
                    <mesh
                      name="polySurface19_lambert2_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.polySurface19_lambert2_0.geometry}
                      material={materials.lambert2}
                    />
                  </group>
                  <group
                    name="polySurface20"
                    position={[-2.071, -1.309, 2.049]}
                    rotation={[0, -0.632, 0]}
                    scale={[0.963, 1, 1.102]}>
                    <mesh
                      name="polySurface20_lambert2_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.polySurface20_lambert2_0.geometry}
                      material={materials.lambert2}
                    />
                  </group>
                  <group
                    name="polySurface21"
                    position={[2.598, -1.309, 2.158]}
                    scale={[0.97, 1, 1.098]}>
                    <mesh
                      name="polySurface21_lambert2_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.polySurface21_lambert2_0.geometry}
                      material={materials.lambert2}
                    />
                  </group>
                  <group name="polySurface22" position={[-0.569, 0.478, -0.001]}>
                    <mesh
                      name="polySurface22_lambert2_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.polySurface22_lambert2_0.geometry}
                      material={materials.lambert2}
                    />
                  </group>
                  <group name="polySurface23" position={[-3.9, -1.094, -0.009]}>
                    <mesh
                      name="polySurface23_lambert2_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.polySurface23_lambert2_0.geometry}
                      material={materials.lambert2}
                    />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/environment_relic_pixel_textured.glb')

export default Earth