/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Master Galanodel (https://sketchfab.com/Master_Galanodel)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/leila-packett-f4e0d4e3cde54355ad169cf2972cd530
Title: Leila Packett
*/

import React, { useRef ,useEffect} from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useCharacterAnimations } from "../models/Contexts/CharcaterAnimation";


const Lelia=(props) =>{
    const { animation, ...rest } = props;
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/leila_packett.glb')
  const { actions,names } = useAnimations(animations, group)
  const { setAnimations, animationIndex } = useCharacterAnimations();
    console.log(names)

  useEffect(() => {
    if (animation && actions[animation]) {
      actions[animation].reset().fadeIn(0.5).play();
      return () => actions[animation].fadeOut(0.5);
    }
  }, [animation, actions]);


  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, Math.PI]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="_150">
                <group name="BodyRoot_149" position={[0, 0.875, 0]}>
                  <group name="cylinder_0" position={[0, -0.25, 0]}>
                    <mesh
                      name="Object_6"
                      castShadow
                      receiveShadow
                      geometry={nodes.Object_6.geometry}
                      material={materials.material_0}
                    />
                  </group>
                  <group name="sphere_1">
                    <mesh
                      name="Object_8"
                      castShadow
                      receiveShadow
                      geometry={nodes.Object_8.geometry}
                      material={materials.material_0}
                    />
                  </group>
                  <group name="HeadBase_100" position={[0, 0.188, 0]}>
                    <group name="sphere_2" position={[0, 0.188, 0]}>
                      <mesh
                        name="Object_11"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_11.geometry}
                        material={materials.material_0}
                      />
                    </group>
                    <group name="sphere_3" position={[0, 0.188, 0]}>
                      <mesh
                        name="Object_13"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_13.geometry}
                        material={materials.material_0}
                      />
                    </group>
                    <group name="TopLip_5" position={[0, 0.1, -0.209]}>
                      <group name="sphere_selection_selection_4" position={[0, 0.087, 0.209]}>
                        <mesh
                          name="Object_16"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_16.geometry}
                          material={materials.material_0}
                        />
                      </group>
                    </group>
                    <group name="TopLip2_7" position={[0, 0.1, -0.209]}>
                      <group name="sphere_selection_selection_6" position={[0, 0.087, 0.209]}>
                        <mesh
                          name="Object_19"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_19.geometry}
                          material={materials.material_0}
                        />
                      </group>
                    </group>
                    <group name="TopTeeth_9" position={[0, 0.1, -0.194]}>
                      <group name="sphere_selection_selection_8" position={[0, 0.087, 0.209]}>
                        <mesh
                          name="Object_22"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_22.geometry}
                          material={materials.material_0}
                        />
                      </group>
                    </group>
                    <group name="BottomLip_11" position={[0, 0.002, -0.155]}>
                      <group name="sphere_selection_10" position={[0, 0.186, 0.155]}>
                        <mesh
                          name="Object_25"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_25.geometry}
                          material={materials.material_0}
                        />
                      </group>
                    </group>
                    <group name="BottomLip2_13" position={[0, 0.002, -0.155]}>
                      <group name="sphere_selection_12" position={[0, 0.186, 0.155]}>
                        <mesh
                          name="Object_28"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_28.geometry}
                          material={materials.material_0}
                        />
                      </group>
                    </group>
                    <group name="BottomTeeth_15" position={[0, 0.002, -0.139]}>
                      <group name="sphere_selection_14" position={[0, 0.186, 0.155]}>
                        <mesh
                          name="Object_31"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_31.geometry}
                          material={materials.material_0}
                        />
                      </group>
                    </group>
                    <group name="LeftCheek_17" position={[-0.075, 0.047, -0.175]}>
                      <group name="sphere_selection_selection_16" position={[0.075, 0.141, 0.237]}>
                        <mesh
                          name="Object_34"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_34.geometry}
                          material={materials.material_0}
                        />
                      </group>
                    </group>
                    <group name="RightCheek_19" position={[0.075, 0.047, -0.175]}>
                      <group name="sphere_selection_selection_18" position={[-0.075, 0.141, 0.237]}>
                        <mesh
                          name="Object_37"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_37.geometry}
                          material={materials.material_0}
                        />
                      </group>
                    </group>
                    <group name="MouthExterior_26" position={[0, 0.047, -0.191]}>
                      <group name="TopMouth_25">
                        <group name="cube_20">
                          <mesh
                            name="Object_41"
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_41.geometry}
                            material={materials.material_0}
                          />
                        </group>
                        <group
                          name="TopMouthRight_22"
                          position={[0.027, 0, 0]}
                          rotation={[0, -0.262, 0]}>
                          <group name="cube_21" position={[0.027, 0, 0]}>
                            <mesh
                              name="Object_44"
                              castShadow
                              receiveShadow
                              geometry={nodes.Object_44.geometry}
                              material={materials.material_0}
                            />
                          </group>
                        </group>
                        <group
                          name="TopMouthLeft_24"
                          position={[-0.027, 0, 0]}
                          rotation={[0, 0.262, 0]}>
                          <group name="cube_23" position={[-0.027, 0, 0]}>
                            <mesh
                              name="Object_47"
                              castShadow
                              receiveShadow
                              geometry={nodes.Object_47.geometry}
                              material={materials.material_0}
                            />
                          </group>
                        </group>
                      </group>
                    </group>
                    <group name="EyeLeft_30" position={[-0.084, 0.188, -0.203]}>
                      <group name="sphere_27">
                        <mesh
                          name="Object_50"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_50.geometry}
                          material={materials.material_0}
                        />
                      </group>
                      <group name="sphere_28" position={[0, 0.016, 0]} rotation={[0, 0, -0.262]}>
                        <mesh
                          name="Object_52"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_52.geometry}
                          material={materials.material_0}
                        />
                      </group>
                      <group name="sphere_29" position={[0, 0.016, 0]} rotation={[0, 0, 0.175]}>
                        <mesh
                          name="Object_54"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_54.geometry}
                          material={materials.material_0}
                        />
                      </group>
                    </group>
                    <group name="EyeLeft2_32" position={[-0.084, 0.094, -0.188]}>
                      <group name="sphere_31">
                        <mesh
                          name="Object_57"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_57.geometry}
                          material={materials.material_0}
                        />
                      </group>
                    </group>
                    <group name="EyeLeft3_34" position={[-0.084, 0.281, -0.188]}>
                      <group name="sphere_33">
                        <mesh
                          name="Object_60"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_60.geometry}
                          material={materials.material_0}
                        />
                      </group>
                    </group>
                    <group name="EyeRight_38" position={[0.084, 0.188, -0.203]}>
                      <group name="sphere_35">
                        <mesh
                          name="Object_63"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_63.geometry}
                          material={materials.material_0}
                        />
                      </group>
                      <group name="sphere_36" position={[0, 0.016, 0]} rotation={[0, 0, 0.262]}>
                        <mesh
                          name="Object_65"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_65.geometry}
                          material={materials.material_0}
                        />
                      </group>
                      <group name="sphere_37" position={[0, 0.016, 0]} rotation={[0, 0, -0.175]}>
                        <mesh
                          name="Object_67"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_67.geometry}
                          material={materials.material_0}
                        />
                      </group>
                    </group>
                    <group name="EyeRight3_40" position={[0.084, 0.281, -0.188]}>
                      <group name="sphere_39">
                        <mesh
                          name="Object_70"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_70.geometry}
                          material={materials.material_0}
                        />
                      </group>
                    </group>
                    <group name="EyeRight2_42" position={[0.084, 0.094, -0.188]}>
                      <group name="sphere_41">
                        <mesh
                          name="Object_73"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_73.geometry}
                          material={materials.material_0}
                        />
                      </group>
                    </group>
                    <group name="Eyebrowleft_44" position={[-0.078, 0.305, -0.172]}>
                      <group
                        name="pyramid_43"
                        position={[-0.031, 0.008, 0]}
                        rotation={[0.031, 0.014, -1.494]}>
                        <mesh
                          name="Object_76"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_76.geometry}
                          material={materials.material_0}
                        />
                      </group>
                    </group>
                    <group name="Eyebrowright_46" position={[0.078, 0.305, -0.172]}>
                      <group
                        name="pyramid_45"
                        position={[0.031, 0.008, 0]}
                        rotation={[0.031, -0.014, 1.494]}>
                        <mesh
                          name="Object_79"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_79.geometry}
                          material={materials.material_0}
                        />
                      </group>
                    </group>
                    <group name="HairBones_99" position={[0, 0.156, 0]}>
                      <group name="sphere_47">
                        <mesh
                          name="Object_82"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_82.geometry}
                          material={materials.material_0}
                        />
                      </group>
                      <group name="pyramid_48" position={[0, 0.063, 0.156]}>
                        <mesh
                          name="Object_84"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_84.geometry}
                          material={materials.material_0}
                        />
                      </group>
                      <group name="pyramid_49" position={[0, 0.063, 0.156]}>
                        <mesh
                          name="Object_86"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_86.geometry}
                          material={materials.material_0}
                        />
                      </group>
                      <group name="pyramid_50" position={[0, 0.063, 0.156]}>
                        <mesh
                          name="Object_88"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_88.geometry}
                          material={materials.material_0}
                        />
                      </group>
                      <group name="cube_51" rotation={[0, Math.PI / 4, 0]}>
                        <mesh
                          name="Object_90"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_90.geometry}
                          material={materials.material_0}
                        />
                      </group>
                      <group name="cube_52">
                        <mesh
                          name="Object_92"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_92.geometry}
                          material={materials.material_0}
                        />
                      </group>
                      <group name="cube_53">
                        <mesh
                          name="Object_94"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_94.geometry}
                          material={materials.material_0}
                        />
                      </group>
                      <group name="cube_54" rotation={[0, -Math.PI / 4, 0]}>
                        <mesh
                          name="Object_96"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_96.geometry}
                          material={materials.material_0}
                        />
                      </group>
                      <group name="pyramid_55" position={[0, 0.063, 0.156]}>
                        <mesh
                          name="Object_98"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_98.geometry}
                          material={materials.material_0}
                        />
                      </group>
                      <group name="BackHairBase_89" position={[0, 0.109, 0.188]}>
                        <group name="pyramid_56" rotation={[0.285, 0.274, 0.746]}>
                          <mesh
                            name="Object_101"
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_101.geometry}
                            material={materials.material_0}
                          />
                        </group>
                        <group name="pyramid_57" rotation={[0.285, -0.274, -0.746]}>
                          <mesh
                            name="Object_103"
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_103.geometry}
                            material={materials.material_0}
                          />
                        </group>
                        <group name="pyramid_58" rotation={[Math.PI / 8, 0, 0]}>
                          <mesh
                            name="Object_105"
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_105.geometry}
                            material={materials.material_0}
                          />
                        </group>
                        <group name="BackHairMiddle1_88" position={[0, 0, 0.016]}>
                          <group name="pyramid_59" position={[0, -0.938, 0]}>
                            <mesh
                              name="Object_108"
                              castShadow
                              receiveShadow
                              geometry={nodes.Object_108.geometry}
                              material={materials.material_0}
                            />
                          </group>
                          <group name="BackHairMiddle2_67" position={[0, -0.188, 0]}>
                            <group name="pyramid_60" position={[0, -0.938, 0]}>
                              <mesh
                                name="Object_111"
                                castShadow
                                receiveShadow
                                geometry={nodes.Object_111.geometry}
                                material={materials.material_0}
                              />
                            </group>
                            <group name="BackHairMiddle3_66" position={[0, -0.188, 0]}>
                              <group name="pyramid_61" position={[0, -0.938, 0]}>
                                <mesh
                                  name="Object_114"
                                  castShadow
                                  receiveShadow
                                  geometry={nodes.Object_114.geometry}
                                  material={materials.material_0}
                                />
                              </group>
                              <group name="BackHairMiddle4_65" position={[0, -0.188, 0]}>
                                <group name="pyramid_62" position={[0, -0.938, 0]}>
                                  <mesh
                                    name="Object_117"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Object_117.geometry}
                                    material={materials.material_0}
                                  />
                                </group>
                                <group name="BackHairMiddle5_64" position={[0, -0.188, 0]}>
                                  <group name="pyramid_63" position={[0, -0.938, 0]}>
                                    <mesh
                                      name="Object_120"
                                      castShadow
                                      receiveShadow
                                      geometry={nodes.Object_120.geometry}
                                      material={materials.material_0}
                                    />
                                  </group>
                                </group>
                              </group>
                            </group>
                          </group>
                          <group name="BackHairLeft1_77" position={[-0.063, -0.063, 0]}>
                            <group name="pyramid_68" position={[0, -0.938, 0]}>
                              <mesh
                                name="Object_123"
                                castShadow
                                receiveShadow
                                geometry={nodes.Object_123.geometry}
                                material={materials.material_0}
                              />
                            </group>
                            <group name="BackHairLeft2_76" position={[0, -0.188, 0]}>
                              <group name="pyramid_69" position={[0, -0.938, 0]}>
                                <mesh
                                  name="Object_126"
                                  castShadow
                                  receiveShadow
                                  geometry={nodes.Object_126.geometry}
                                  material={materials.material_0}
                                />
                              </group>
                              <group name="BackHairLeft3_75" position={[0, -0.188, 0]}>
                                <group name="pyramid_70" position={[0, -0.938, 0]}>
                                  <mesh
                                    name="Object_129"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Object_129.geometry}
                                    material={materials.material_0}
                                  />
                                </group>
                                <group name="BackHairLeft4_74" position={[0, -0.188, 0]}>
                                  <group name="pyramid_71" position={[0, -0.938, 0]}>
                                    <mesh
                                      name="Object_132"
                                      castShadow
                                      receiveShadow
                                      geometry={nodes.Object_132.geometry}
                                      material={materials.material_0}
                                    />
                                  </group>
                                  <group name="BackHairLeft5_73" position={[0, -0.188, 0]}>
                                    <group name="pyramid_72" position={[0, -0.938, 0]}>
                                      <mesh
                                        name="Object_135"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.Object_135.geometry}
                                        material={materials.material_0}
                                      />
                                    </group>
                                  </group>
                                </group>
                              </group>
                            </group>
                          </group>
                          <group name="BackHairRight1_87" position={[0.063, -0.063, 0]}>
                            <group name="pyramid_78" position={[0, -0.938, 0]}>
                              <mesh
                                name="Object_138"
                                castShadow
                                receiveShadow
                                geometry={nodes.Object_138.geometry}
                                material={materials.material_0}
                              />
                            </group>
                            <group name="BackHairRight2_86" position={[0, -0.188, 0]}>
                              <group name="pyramid_79" position={[0, -0.938, 0]}>
                                <mesh
                                  name="Object_141"
                                  castShadow
                                  receiveShadow
                                  geometry={nodes.Object_141.geometry}
                                  material={materials.material_0}
                                />
                              </group>
                              <group name="BackHairRight3_85" position={[0, -0.188, 0]}>
                                <group name="pyramid_80" position={[0, -0.938, 0]}>
                                  <mesh
                                    name="Object_144"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Object_144.geometry}
                                    material={materials.material_0}
                                  />
                                </group>
                                <group name="BackHairRight4_84" position={[0, -0.188, 0]}>
                                  <group name="pyramid_81" position={[0, -0.938, 0]}>
                                    <mesh
                                      name="Object_147"
                                      castShadow
                                      receiveShadow
                                      geometry={nodes.Object_147.geometry}
                                      material={materials.material_0}
                                    />
                                  </group>
                                  <group name="BackHairRight5_83" position={[0, -0.188, 0]}>
                                    <group name="pyramid_82" position={[0, -0.938, 0]}>
                                      <mesh
                                        name="Object_150"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.Object_150.geometry}
                                        material={materials.material_0}
                                      />
                                    </group>
                                  </group>
                                </group>
                              </group>
                            </group>
                          </group>
                        </group>
                      </group>
                      <group
                        name="FrontSpike2_92"
                        position={[0, 0.188, -0.125]}
                        rotation={[-Math.PI / 8, 0, 0]}>
                        <group name="pyramid_90" rotation={[-Math.PI, 0, 0]}>
                          <mesh
                            name="Object_153"
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_153.geometry}
                            material={materials.material_0}
                          />
                        </group>
                        <group name="pyramid_91" rotation={[-Math.PI / 4, 0, 0]}>
                          <mesh
                            name="Object_155"
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_155.geometry}
                            material={materials.material_0}
                          />
                        </group>
                      </group>
                      <group
                        name="FrontSpike_95"
                        position={[0, 0.188, -0.172]}
                        rotation={[-Math.PI / 4, 0, 0]}>
                        <group name="pyramid_93" rotation={[-Math.PI, 0, 0]}>
                          <mesh
                            name="Object_158"
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_158.geometry}
                            material={materials.material_0}
                          />
                        </group>
                        <group name="pyramid_94" rotation={[-Math.PI / 4, 0, 0]}>
                          <mesh
                            name="Object_160"
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_160.geometry}
                            material={materials.material_0}
                          />
                        </group>
                      </group>
                      <group
                        name="FrontSpike3_98"
                        position={[0, 0.172, -0.109]}
                        rotation={[-0.131, 0, 0]}>
                        <group name="pyramid_96" rotation={[-2.749, 0, 0]}>
                          <mesh
                            name="Object_163"
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_163.geometry}
                            material={materials.material_0}
                          />
                        </group>
                        <group name="pyramid_97" rotation={[-Math.PI / 8, 0, 0]}>
                          <mesh
                            name="Object_165"
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_165.geometry}
                            material={materials.material_0}
                          />
                        </group>
                      </group>
                    </group>
                  </group>
                  <group name="Torso_114" position={[0, -0.188, 0]}>
                    <group name="cylinder_101">
                      <mesh
                        name="Object_168"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_168.geometry}
                        material={materials.material_0}
                      />
                    </group>
                    <group name="LeftLeg_107" position={[-0.031, -0.031, 0]}>
                      <group name="cylinder_102">
                        <mesh
                          name="Object_171"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_171.geometry}
                          material={materials.material_0}
                        />
                      </group>
                      <group name="LeftThigh_106" position={[0, -0.281, 0]}>
                        <group name="cylinder_103" position={[0, -0.031, 0]}>
                          <mesh
                            name="Object_174"
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_174.geometry}
                            material={materials.material_0}
                          />
                        </group>
                        <group name="LeftFoot_105" position={[0, -0.375, 0]}>
                          <group name="cylinder_104">
                            <mesh
                              name="Object_177"
                              castShadow
                              receiveShadow
                              geometry={nodes.Object_177.geometry}
                              material={materials.material_0}
                            />
                          </group>
                        </group>
                      </group>
                    </group>
                    <group name="RightLeg_113" position={[0.031, -0.031, 0]}>
                      <group name="cylinder_108">
                        <mesh
                          name="Object_180"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_180.geometry}
                          material={materials.material_0}
                        />
                      </group>
                      <group name="RightThigh_112" position={[0, -0.281, 0]}>
                        <group name="cylinder_109" position={[0, -0.031, 0]}>
                          <mesh
                            name="Object_183"
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_183.geometry}
                            material={materials.material_0}
                          />
                        </group>
                        <group name="RightFoot_111" position={[0, -0.375, 0]}>
                          <group name="cylinder_110">
                            <mesh
                              name="Object_186"
                              castShadow
                              receiveShadow
                              geometry={nodes.Object_186.geometry}
                              material={materials.material_0}
                            />
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                  <group name="LeftShoulder_131" position={[-0.063, 0.125, 0]}>
                    <group name="sphere_115">
                      <mesh
                        name="Object_189"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_189.geometry}
                        material={materials.material_0}
                      />
                    </group>
                    <group name="cylinder_116" rotation={[0, 0, Math.PI / 2]}>
                      <mesh
                        name="Object_191"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_191.geometry}
                        material={materials.material_0}
                      />
                    </group>
                    <group name="LeftArm_130" position={[-0.031, 0, 0]}>
                      <group name="cylinder_117" rotation={[0, 0, Math.PI / 2]}>
                        <mesh
                          name="Object_194"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_194.geometry}
                          material={materials.material_0}
                        />
                      </group>
                      <group name="LeftForeArm_129" position={[-0.234, 0, 0]}>
                        <group name="cylinder_118" rotation={[0, 0, Math.PI / 2]}>
                          <mesh
                            name="Object_197"
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_197.geometry}
                            material={materials.material_0}
                          />
                        </group>
                        <group name="Lefthand_128" position={[-0.25, 0, 0]}>
                          <group name="sphere_119">
                            <mesh
                              name="Object_200"
                              castShadow
                              receiveShadow
                              geometry={nodes.Object_200.geometry}
                              material={materials.material_0}
                            />
                          </group>
                          <group name="LeftFingersBase_123" position={[0, 0.023, 0]}>
                            <group name="cylinder_120" rotation={[0, 0, Math.PI / 2]}>
                              <mesh
                                name="Object_203"
                                castShadow
                                receiveShadow
                                geometry={nodes.Object_203.geometry}
                                material={materials.material_0}
                              />
                            </group>
                            <group name="LeftFingersTip_122" position={[-0.078, 0, 0]}>
                              <group name="cylinder_121" rotation={[0, 0, Math.PI / 2]}>
                                <mesh
                                  name="Object_206"
                                  castShadow
                                  receiveShadow
                                  geometry={nodes.Object_206.geometry}
                                  material={materials.material_0}
                                />
                              </group>
                            </group>
                          </group>
                          <group name="LeftThumbBase_127" position={[0, 0, -0.039]}>
                            <group name="sphere_124">
                              <mesh
                                name="Object_209"
                                castShadow
                                receiveShadow
                                geometry={nodes.Object_209.geometry}
                                material={materials.material_0}
                              />
                            </group>
                            <group name="LeftThumbTip_126" position={[0, 0, -0.031]}>
                              <group name="sphere_125" position={[0, 0, -0.016]}>
                                <mesh
                                  name="Object_212"
                                  castShadow
                                  receiveShadow
                                  geometry={nodes.Object_212.geometry}
                                  material={materials.material_0}
                                />
                              </group>
                            </group>
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                  <group name="RightShoulder_148" position={[0.063, 0.125, 0]}>
                    <group name="sphere_132">
                      <mesh
                        name="Object_215"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_215.geometry}
                        material={materials.material_0}
                      />
                    </group>
                    <group name="cylinder_133" rotation={[0, 0, -Math.PI / 2]}>
                      <mesh
                        name="Object_217"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_217.geometry}
                        material={materials.material_0}
                      />
                    </group>
                    <group name="RightArm_147" position={[0.031, 0, 0]}>
                      <group name="cylinder_134" rotation={[0, 0, -Math.PI / 2]}>
                        <mesh
                          name="Object_220"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_220.geometry}
                          material={materials.material_0}
                        />
                      </group>
                      <group name="RightForeArm_146" position={[0.234, 0, 0]}>
                        <group name="cylinder_135" rotation={[0, 0, -Math.PI / 2]}>
                          <mesh
                            name="Object_223"
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_223.geometry}
                            material={materials.material_0}
                          />
                        </group>
                        <group name="Righthand_145" position={[0.25, 0, 0]}>
                          <group name="sphere_136">
                            <mesh
                              name="Object_226"
                              castShadow
                              receiveShadow
                              geometry={nodes.Object_226.geometry}
                              material={materials.material_0}
                            />
                          </group>
                          <group name="RightFingersBase_140" position={[0, 0.023, 0]}>
                            <group name="cylinder_137" rotation={[0, 0, -Math.PI / 2]}>
                              <mesh
                                name="Object_229"
                                castShadow
                                receiveShadow
                                geometry={nodes.Object_229.geometry}
                                material={materials.material_0}
                              />
                            </group>
                            <group name="RightFingersTip_139" position={[0.078, 0, 0]}>
                              <group name="cylinder_138" rotation={[0, 0, -Math.PI / 2]}>
                                <mesh
                                  name="Object_232"
                                  castShadow
                                  receiveShadow
                                  geometry={nodes.Object_232.geometry}
                                  material={materials.material_0}
                                />
                              </group>
                            </group>
                          </group>
                          <group name="RightThumbBase_144" position={[0, 0, -0.039]}>
                            <group name="sphere_141">
                              <mesh
                                name="Object_235"
                                castShadow
                                receiveShadow
                                geometry={nodes.Object_235.geometry}
                                material={materials.material_0}
                              />
                            </group>
                            <group name="RightThumbTip_143" position={[0, 0, -0.031]}>
                              <group name="sphere_142" position={[0, 0, -0.016]}>
                                <mesh
                                  name="Object_238"
                                  castShadow
                                  receiveShadow
                                  geometry={nodes.Object_238.geometry}
                                  material={materials.material_0}
                                />
                              </group>
                            </group>
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/leila_packett.glb')

export default Lelia;
