/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Master Galanodel (https://sketchfab.com/Master_Galanodel)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/milo-pattelle-3922b314c73b464493f97d7f9d73ac8b
Title: Milo Pattelle
*/

import React, { useRef,useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

const Milo=(props) =>{
    const { animation, ...rest } = props;
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/milo_pattelle.glb')
  const { actions,names } = useAnimations(animations, group)
  console.log(names);

  useEffect(() => {
    if (animation && actions[animation]) {
      actions[animation].reset().fadeIn(0.5).play();
      return () => actions[animation].fadeOut(0.5);
    }
  }, [animation, actions]);



  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, Math.PI]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="_136">
                <group name="BodyRoot_135" position={[0, 0.875, 0]}>
                  <group name="cylinder_0" position={[0, -0.25, 0]}>
                    <mesh
                      name="Object_6"
                      castShadow
                      receiveShadow
                      geometry={nodes.Object_6.geometry}
                      material={materials.material_0}
                    />
                  </group>
                  <group name="sphere_1">
                    <mesh
                      name="Object_8"
                      castShadow
                      receiveShadow
                      geometry={nodes.Object_8.geometry}
                      material={materials.material_0}
                    />
                  </group>
                  <group name="HeadBase_79" position={[0, 0.188, 0]}>
                    <group name="sphere_2" position={[0, 0.188, 0]}>
                      <mesh
                        name="Object_11"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_11.geometry}
                        material={materials.material_0}
                      />
                    </group>
                    <group name="sphere_3" position={[0, 0.188, 0]}>
                      <mesh
                        name="Object_13"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_13.geometry}
                        material={materials.material_0}
                      />
                    </group>
                    <group name="TopLip_5" position={[0, 0.1, -0.209]}>
                      <group name="sphere_selection_selection_4" position={[0, 0.087, 0.209]}>
                        <mesh
                          name="Object_16"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_16.geometry}
                          material={materials.material_0}
                        />
                      </group>
                    </group>
                    <group name="TopLip2_7" position={[0, 0.1, -0.209]}>
                      <group name="sphere_selection_selection_6" position={[0, 0.087, 0.209]}>
                        <mesh
                          name="Object_19"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_19.geometry}
                          material={materials.material_0}
                        />
                      </group>
                    </group>
                    <group name="TopTeeth_9" position={[0, 0.1, -0.194]}>
                      <group name="sphere_selection_selection_8" position={[0, 0.087, 0.209]}>
                        <mesh
                          name="Object_22"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_22.geometry}
                          material={materials.material_0}
                        />
                      </group>
                    </group>
                    <group name="BottomLip_11" position={[0, 0.002, -0.155]}>
                      <group name="sphere_selection_10" position={[0, 0.186, 0.155]}>
                        <mesh
                          name="Object_25"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_25.geometry}
                          material={materials.material_0}
                        />
                      </group>
                    </group>
                    <group name="BottomLip2_13" position={[0, 0.002, -0.155]}>
                      <group name="sphere_selection_12" position={[0, 0.186, 0.155]}>
                        <mesh
                          name="Object_28"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_28.geometry}
                          material={materials.material_0}
                        />
                      </group>
                    </group>
                    <group name="BottomTeeth_15" position={[0, 0.002, -0.139]}>
                      <group name="sphere_selection_14" position={[0, 0.186, 0.155]}>
                        <mesh
                          name="Object_31"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_31.geometry}
                          material={materials.material_0}
                        />
                      </group>
                    </group>
                    <group name="LeftCheek_17" position={[-0.075, 0.047, -0.175]}>
                      <group name="sphere_selection_selection_16" position={[0.075, 0.141, 0.237]}>
                        <mesh
                          name="Object_34"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_34.geometry}
                          material={materials.material_0}
                        />
                      </group>
                    </group>
                    <group name="RightCheek_19" position={[0.075, 0.047, -0.175]}>
                      <group name="sphere_selection_selection_18" position={[-0.075, 0.141, 0.237]}>
                        <mesh
                          name="Object_37"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_37.geometry}
                          material={materials.material_0}
                        />
                      </group>
                    </group>
                    <group name="MouthExterior_26" position={[0, 0.047, -0.191]}>
                      <group name="TopMouth_25">
                        <group name="cube_20">
                          <mesh
                            name="Object_41"
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_41.geometry}
                            material={materials.material_0}
                          />
                        </group>
                        <group
                          name="TopMouthRight_22"
                          position={[0.027, 0, 0]}
                          rotation={[0, -0.262, 0]}>
                          <group name="cube_21" position={[0.027, 0, 0]}>
                            <mesh
                              name="Object_44"
                              castShadow
                              receiveShadow
                              geometry={nodes.Object_44.geometry}
                              material={materials.material_0}
                            />
                          </group>
                        </group>
                        <group
                          name="TopMouthLeft_24"
                          position={[-0.027, 0, 0]}
                          rotation={[0, 0.262, 0]}>
                          <group name="cube_23" position={[-0.027, 0, 0]}>
                            <mesh
                              name="Object_47"
                              castShadow
                              receiveShadow
                              geometry={nodes.Object_47.geometry}
                              material={materials.material_0}
                            />
                          </group>
                        </group>
                      </group>
                    </group>
                    <group name="EyeLeft_34" position={[-0.069, 0.188, -0.203]}>
                      <group name="sphere_27">
                        <mesh
                          name="Object_50"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_50.geometry}
                          material={materials.material_0}
                        />
                      </group>
                      <group
                        name="pyramid_28"
                        position={[-0.041, 0.094, 0.031]}
                        rotation={[0, 0, -1.702]}>
                        <mesh
                          name="Object_52"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_52.geometry}
                          material={materials.material_0}
                        />
                      </group>
                      <group
                        name="pyramid_29"
                        position={[-0.041, 0.016, 0.031]}
                        rotation={[0, 0, 1.702]}>
                        <mesh
                          name="Object_54"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_54.geometry}
                          material={materials.material_0}
                        />
                      </group>
                      <group name="EyeLeft2_31" position={[0, 0.078, 0]}>
                        <group name="sphere_30">
                          <mesh
                            name="Object_57"
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_57.geometry}
                            material={materials.material_0}
                          />
                        </group>
                      </group>
                      <group name="EyeLeft3_33" position={[0, -0.094, 0]}>
                        <group name="sphere_32">
                          <mesh
                            name="Object_60"
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_60.geometry}
                            material={materials.material_0}
                          />
                        </group>
                      </group>
                    </group>
                    <group name="EyeRight_42" position={[0.069, 0.188, -0.203]}>
                      <group name="sphere_35">
                        <mesh
                          name="Object_63"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_63.geometry}
                          material={materials.material_0}
                        />
                      </group>
                      <group
                        name="pyramid_36"
                        position={[0.041, 0.094, 0.031]}
                        rotation={[0, 0, 1.702]}>
                        <mesh
                          name="Object_65"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_65.geometry}
                          material={materials.material_0}
                        />
                      </group>
                      <group
                        name="pyramid_37"
                        position={[0.041, 0.016, 0.031]}
                        rotation={[0, 0, -1.702]}>
                        <mesh
                          name="Object_67"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_67.geometry}
                          material={materials.material_0}
                        />
                      </group>
                      <group name="EyeRight2_39" position={[0, 0.078, 0]}>
                        <group name="sphere_38">
                          <mesh
                            name="Object_70"
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_70.geometry}
                            material={materials.material_0}
                          />
                        </group>
                      </group>
                      <group name="EyeRight3_41" position={[0, -0.094, 0]}>
                        <group name="sphere_40">
                          <mesh
                            name="Object_73"
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_73.geometry}
                            material={materials.material_0}
                          />
                        </group>
                      </group>
                    </group>
                    <group name="Eyebrowleft_44" position={[-0.078, 0.305, -0.172]}>
                      <group
                        name="pyramid_43"
                        position={[-0.031, 0.008, 0]}
                        rotation={[0.031, 0.014, -1.494]}>
                        <mesh
                          name="Object_76"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_76.geometry}
                          material={materials.material_0}
                        />
                      </group>
                    </group>
                    <group name="Eyebrowright_46" position={[0.078, 0.305, -0.172]}>
                      <group
                        name="pyramid_45"
                        position={[0.031, 0.008, 0]}
                        rotation={[0.031, -0.014, 1.494]}>
                        <mesh
                          name="Object_79"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_79.geometry}
                          material={materials.material_0}
                        />
                      </group>
                    </group>
                    <group name="HairBones_78" position={[0, 0.156, 0]}>
                      <group name="sphere_47">
                        <mesh
                          name="Object_82"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_82.geometry}
                          material={materials.material_0}
                        />
                      </group>
                      <group name="BackHairBase_65" position={[0, 0.125, 0.172]}>
                        <group name="pyramid_48" rotation={[1.07, 0.274, 0.746]}>
                          <mesh
                            name="Object_85"
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_85.geometry}
                            material={materials.material_0}
                          />
                        </group>
                        <group name="pyramid_49" rotation={[1.07, -0.274, -0.746]}>
                          <mesh
                            name="Object_87"
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_87.geometry}
                            material={materials.material_0}
                          />
                        </group>
                        <group name="pyramid_50" rotation={[1.178, 0, 0]}>
                          <mesh
                            name="Object_89"
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_89.geometry}
                            material={materials.material_0}
                          />
                        </group>
                        <group name="BackHairMiddle1_64" position={[0, 0, 0.016]}>
                          <group name="pyramid_51" position={[0, -0.938, 0]}>
                            <mesh
                              name="Object_92"
                              castShadow
                              receiveShadow
                              geometry={nodes.Object_92.geometry}
                              material={materials.material_0}
                            />
                          </group>
                          <group name="BackHairMiddle2_55" position={[0, -0.188, 0]}>
                            <group name="pyramid_52" position={[0, -0.938, 0]}>
                              <mesh
                                name="Object_95"
                                castShadow
                                receiveShadow
                                geometry={nodes.Object_95.geometry}
                                material={materials.material_0}
                              />
                            </group>
                            <group name="BackHairMiddle3_54" position={[0, -0.188, 0]}>
                              <group name="pyramid_53" position={[0, -0.938, 0]}>
                                <mesh
                                  name="Object_98"
                                  castShadow
                                  receiveShadow
                                  geometry={nodes.Object_98.geometry}
                                  material={materials.material_0}
                                />
                              </group>
                            </group>
                          </group>
                          <group name="BackHairLeft1_59" position={[-0.063, -0.063, 0]}>
                            <group name="pyramid_56" position={[0, -0.938, 0]}>
                              <mesh
                                name="Object_101"
                                castShadow
                                receiveShadow
                                geometry={nodes.Object_101.geometry}
                                material={materials.material_0}
                              />
                            </group>
                            <group name="BackHairLeft2_58" position={[0, -0.188, 0]}>
                              <group name="pyramid_57" position={[0, -0.938, 0]}>
                                <mesh
                                  name="Object_104"
                                  castShadow
                                  receiveShadow
                                  geometry={nodes.Object_104.geometry}
                                  material={materials.material_0}
                                />
                              </group>
                            </group>
                          </group>
                          <group name="BackHairRight1_63" position={[0.063, -0.063, 0]}>
                            <group name="pyramid_60" position={[0, -0.938, 0]}>
                              <mesh
                                name="Object_107"
                                castShadow
                                receiveShadow
                                geometry={nodes.Object_107.geometry}
                                material={materials.material_0}
                              />
                            </group>
                            <group name="BackHairRight2_62" position={[0, -0.188, 0]}>
                              <group name="pyramid_61" position={[0, -0.938, 0]}>
                                <mesh
                                  name="Object_110"
                                  castShadow
                                  receiveShadow
                                  geometry={nodes.Object_110.geometry}
                                  material={materials.material_0}
                                />
                              </group>
                            </group>
                          </group>
                        </group>
                      </group>
                      <group name="FrontSpike_68" position={[0.125, 0.125, -0.094]}>
                        <group name="pyramid_66">
                          <mesh
                            name="Object_113"
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_113.geometry}
                            material={materials.material_0}
                          />
                        </group>
                        <group name="pyramid_67" position={[0, -0.063, 0]}>
                          <mesh
                            name="Object_115"
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_115.geometry}
                            material={materials.material_0}
                          />
                        </group>
                      </group>
                      <group name="FrontSpike3_71" position={[-0.125, 0.125, -0.094]}>
                        <group name="pyramid_69">
                          <mesh
                            name="Object_118"
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_118.geometry}
                            material={materials.material_0}
                          />
                        </group>
                        <group name="pyramid_70" position={[0, -0.063, 0]}>
                          <mesh
                            name="Object_120"
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_120.geometry}
                            material={materials.material_0}
                          />
                        </group>
                      </group>
                      <group name="FrontSpike2_74" position={[0.188, 0.031, -0.094]}>
                        <group name="pyramid_72">
                          <mesh
                            name="Object_123"
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_123.geometry}
                            material={materials.material_0}
                          />
                        </group>
                        <group name="pyramid_73" position={[0, -0.063, 0]}>
                          <mesh
                            name="Object_125"
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_125.geometry}
                            material={materials.material_0}
                          />
                        </group>
                      </group>
                      <group name="FrontSpike4_77" position={[-0.188, 0.031, -0.094]}>
                        <group name="pyramid_75">
                          <mesh
                            name="Object_128"
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_128.geometry}
                            material={materials.material_0}
                          />
                        </group>
                        <group name="pyramid_76" position={[0, -0.063, 0]}>
                          <mesh
                            name="Object_130"
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_130.geometry}
                            material={materials.material_0}
                          />
                        </group>
                      </group>
                    </group>
                  </group>
                  <group name="Torso_93" position={[0, -0.188, 0]}>
                    <group name="cylinder_80">
                      <mesh
                        name="Object_133"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_133.geometry}
                        material={materials.material_0}
                      />
                    </group>
                    <group name="LeftLeg_86" position={[-0.031, -0.031, 0]}>
                      <group name="cylinder_81">
                        <mesh
                          name="Object_136"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_136.geometry}
                          material={materials.material_0}
                        />
                      </group>
                      <group name="LeftThigh_85" position={[0, -0.281, 0]}>
                        <group name="cylinder_82" position={[0, -0.031, 0]}>
                          <mesh
                            name="Object_139"
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_139.geometry}
                            material={materials.material_0}
                          />
                        </group>
                        <group name="LeftFoot_84" position={[0, -0.375, 0]}>
                          <group name="cylinder_83">
                            <mesh
                              name="Object_142"
                              castShadow
                              receiveShadow
                              geometry={nodes.Object_142.geometry}
                              material={materials.material_0}
                            />
                          </group>
                        </group>
                      </group>
                    </group>
                    <group name="RightLeg_92" position={[0.031, -0.031, 0]}>
                      <group name="cylinder_87">
                        <mesh
                          name="Object_145"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_145.geometry}
                          material={materials.material_0}
                        />
                      </group>
                      <group name="RightThigh_91" position={[0, -0.281, 0]}>
                        <group name="cylinder_88" position={[0, -0.031, 0]}>
                          <mesh
                            name="Object_148"
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_148.geometry}
                            material={materials.material_0}
                          />
                        </group>
                        <group name="RightFoot_90" position={[0, -0.375, 0]}>
                          <group name="cylinder_89">
                            <mesh
                              name="Object_151"
                              castShadow
                              receiveShadow
                              geometry={nodes.Object_151.geometry}
                              material={materials.material_0}
                            />
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                  <group name="LeftShoulder_111" position={[-0.063, 0.125, 0]}>
                    <group name="sphere_94">
                      <mesh
                        name="Object_154"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_154.geometry}
                        material={materials.material_0}
                      />
                    </group>
                    <group name="cylinder_95" rotation={[0, 0, Math.PI / 2]}>
                      <mesh
                        name="Object_156"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_156.geometry}
                        material={materials.material_0}
                      />
                    </group>
                    <group name="LeftArm_110" position={[-0.031, 0, 0]}>
                      <group name="cylinder_96" rotation={[0, 0, Math.PI / 2]}>
                        <mesh
                          name="Object_159"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_159.geometry}
                          material={materials.material_0}
                        />
                      </group>
                      <group name="LeftForeArm_109" position={[-0.234, 0, 0]}>
                        <group name="cylinder_97" rotation={[0, 0, Math.PI / 2]}>
                          <mesh
                            name="Object_162"
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_162.geometry}
                            material={materials.material_0}
                          />
                        </group>
                        <group name="cylinder_98" rotation={[0, 0, Math.PI / 2]}>
                          <mesh
                            name="Object_164"
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_164.geometry}
                            material={materials.material_0}
                          />
                        </group>
                        <group name="Lefthand_108" position={[-0.25, 0, 0]}>
                          <group name="sphere_99">
                            <mesh
                              name="Object_167"
                              castShadow
                              receiveShadow
                              geometry={nodes.Object_167.geometry}
                              material={materials.material_0}
                            />
                          </group>
                          <group name="LeftFingersBase_103" position={[0, 0.023, 0]}>
                            <group name="cylinder_100" rotation={[0, 0, Math.PI / 2]}>
                              <mesh
                                name="Object_170"
                                castShadow
                                receiveShadow
                                geometry={nodes.Object_170.geometry}
                                material={materials.material_0}
                              />
                            </group>
                            <group name="LeftFingersTip_102" position={[-0.078, 0, 0]}>
                              <group name="cylinder_101" rotation={[0, 0, Math.PI / 2]}>
                                <mesh
                                  name="Object_173"
                                  castShadow
                                  receiveShadow
                                  geometry={nodes.Object_173.geometry}
                                  material={materials.material_0}
                                />
                              </group>
                            </group>
                          </group>
                          <group name="LeftThumbBase_107" position={[0, 0, -0.039]}>
                            <group name="sphere_104">
                              <mesh
                                name="Object_176"
                                castShadow
                                receiveShadow
                                geometry={nodes.Object_176.geometry}
                                material={materials.material_0}
                              />
                            </group>
                            <group name="LeftThumbTip_106" position={[0, 0, -0.031]}>
                              <group name="sphere_105" position={[0, 0, -0.016]}>
                                <mesh
                                  name="Object_179"
                                  castShadow
                                  receiveShadow
                                  geometry={nodes.Object_179.geometry}
                                  material={materials.material_0}
                                />
                              </group>
                            </group>
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                  <group name="RightShoulder_129" position={[0.063, 0.125, 0]}>
                    <group name="sphere_112">
                      <mesh
                        name="Object_182"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_182.geometry}
                        material={materials.material_0}
                      />
                    </group>
                    <group name="cylinder_113" rotation={[0, 0, -Math.PI / 2]}>
                      <mesh
                        name="Object_184"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_184.geometry}
                        material={materials.material_0}
                      />
                    </group>
                    <group name="RightArm_128" position={[0.031, 0, 0]}>
                      <group name="cylinder_114" rotation={[0, 0, -Math.PI / 2]}>
                        <mesh
                          name="Object_187"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_187.geometry}
                          material={materials.material_0}
                        />
                      </group>
                      <group name="RightForeArm_127" position={[0.234, 0, 0]}>
                        <group name="cylinder_115" rotation={[0, 0, -Math.PI / 2]}>
                          <mesh
                            name="Object_190"
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_190.geometry}
                            material={materials.material_0}
                          />
                        </group>
                        <group name="cylinder_116" rotation={[0, 0, -Math.PI / 2]}>
                          <mesh
                            name="Object_192"
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_192.geometry}
                            material={materials.material_0}
                          />
                        </group>
                        <group name="Righthand_126" position={[0.25, 0, 0]}>
                          <group name="sphere_117">
                            <mesh
                              name="Object_195"
                              castShadow
                              receiveShadow
                              geometry={nodes.Object_195.geometry}
                              material={materials.material_0}
                            />
                          </group>
                          <group name="RightFingersBase_121" position={[0, 0.023, 0]}>
                            <group name="cylinder_118" rotation={[0, 0, -Math.PI / 2]}>
                              <mesh
                                name="Object_198"
                                castShadow
                                receiveShadow
                                geometry={nodes.Object_198.geometry}
                                material={materials.material_0}
                              />
                            </group>
                            <group name="RightFingersTip_120" position={[0.078, 0, 0]}>
                              <group name="cylinder_119" rotation={[0, 0, -Math.PI / 2]}>
                                <mesh
                                  name="Object_201"
                                  castShadow
                                  receiveShadow
                                  geometry={nodes.Object_201.geometry}
                                  material={materials.material_0}
                                />
                              </group>
                            </group>
                          </group>
                          <group name="RightThumbBase_125" position={[0, 0, -0.039]}>
                            <group name="sphere_122">
                              <mesh
                                name="Object_204"
                                castShadow
                                receiveShadow
                                geometry={nodes.Object_204.geometry}
                                material={materials.material_0}
                              />
                            </group>
                            <group name="RightThumbTip_124" position={[0, 0, -0.031]}>
                              <group name="sphere_123" position={[0, 0, -0.016]}>
                                <mesh
                                  name="Object_207"
                                  castShadow
                                  receiveShadow
                                  geometry={nodes.Object_207.geometry}
                                  material={materials.material_0}
                                />
                              </group>
                            </group>
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                  <group name="Jacket_134" position={[0, 0.125, 0]}>
                    <group name="cylinder_130" position={[0, -0.375, 0]}>
                      <mesh
                        name="Object_210"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_210.geometry}
                        material={materials.material_0}
                      />
                    </group>
                    <group name="Hood_133">
                      <group name="sphere_131" position={[0, 0.219, 0]}>
                        <mesh
                          name="Object_213"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_213.geometry}
                          material={materials.material_0}
                        />
                      </group>
                      <group name="sphere_132" position={[0, 0.219, 0]}>
                        <mesh
                          name="Object_215"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_215.geometry}
                          material={materials.material_0}
                        />
                      </group>
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/milo_pattelle.glb')

export default Milo;