/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Master Galanodel (https://sketchfab.com/Master_Galanodel)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sonic-oc-character-base-b5f54a871cfe4217b81f8629b33bd299
Title: Sonic OC character Base
*/

import React, { useRef,useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

const Sonic=(props)=> {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/sonic_oc_character_base.glb')
  const { actions } = useAnimations(animations, group)

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, -3.126]} scale={0.667}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="_57">
                <group name="BodyBase_56" position={[0, 1.188, 0]}>
                  <group name="cube_0" position={[0, 0.25, 0]}>
                    <mesh
                      name="Object_6"
                      castShadow
                      receiveShadow
                      geometry={nodes.Object_6.geometry}
                      material={materials.material_0}
                    />
                  </group>
                  <group name="HeadBones_20" position={[0, 0.563, 0]}>
                    <group name="cube_1">
                      <mesh
                        name="Object_9"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_9.geometry}
                        material={materials.material_0}
                      />
                    </group>
                    <group name="cube_2">
                      <mesh
                        name="Object_11"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_11.geometry}
                        material={materials.material_0}
                      />
                    </group>
                    <group name="cube_3">
                      <mesh
                        name="Object_13"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_13.geometry}
                        material={materials.material_0}
                      />
                    </group>
                    <group name="cube_4">
                      <mesh
                        name="Object_15"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_15.geometry}
                        material={materials.material_0}
                      />
                    </group>
                    <group name="cube_5">
                      <mesh
                        name="Object_17"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_17.geometry}
                        material={materials.material_0}
                      />
                    </group>
                    <group name="Mouth_9" position={[0.063, 0.031, -0.25]}>
                      <group name="cube_6" position={[0, -0.031, 0.25]}>
                        <mesh
                          name="Object_20"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_20.geometry}
                          material={materials.material_0}
                        />
                      </group>
                      <group name="Mouth2_8" position={[-0.063, 0, 0]}>
                        <group name="cube_7" position={[-0.063, -0.031, 0.25]}>
                          <mesh
                            name="Object_23"
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_23.geometry}
                            material={materials.material_0}
                          />
                        </group>
                      </group>
                    </group>
                    <group name="Eyeball_15" position={[0, 0.25, -0.188]}>
                      <group name="cube_10" position={[0, -0.25, 0.188]}>
                        <mesh
                          name="Object_26"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_26.geometry}
                          material={materials.material_0}
                        />
                      </group>
                      <group name="Eye1_12" position={[0.063, 0, -0.063]}>
                        <group name="cube_11" position={[-0.063, -0.25, 0.25]}>
                          <mesh
                            name="Object_29"
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_29.geometry}
                            material={materials.material_0}
                          />
                        </group>
                      </group>
                      <group name="Eye2_14" position={[-0.063, 0, -0.063]}>
                        <group name="cube_13" position={[-0.063, -0.25, 0.25]}>
                          <mesh
                            name="Object_32"
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_32.geometry}
                            material={materials.material_0}
                          />
                        </group>
                      </group>
                    </group>
                    <group name="EyeBrow1_17" position={[0.203, 0.344, -0.25]}>
                      <group name="Eyebrow1_16" position={[-0.203, -0.344, 0.25]}>
                        <mesh
                          name="Object_35"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_35.geometry}
                          material={materials.material_0}
                        />
                      </group>
                    </group>
                    <group name="Eyebrow2_19" position={[-0.203, 0.344, -0.25]}>
                      <group name="Eyebrow2_18" position={[-0.016, 0, 0]}>
                        <mesh
                          name="Object_38"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_38.geometry}
                          material={materials.material_0}
                        />
                      </group>
                    </group>
                  </group>
                  <group name="Arm1_32" position={[-0.188, 0.469, 0]}>
                    <group name="cube_23">
                      <mesh
                        name="Object_41"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_41.geometry}
                        material={materials.material_0}
                      />
                    </group>
                    <group name="LowerArm1_31" position={[-0.313, 0.031, -0.031]}>
                      <group name="cube_24" position={[0.313, -0.031, 0.031]}>
                        <mesh
                          name="Object_44"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_44.geometry}
                          material={materials.material_0}
                        />
                      </group>
                      <group name="Hand1_30" position={[-0.313, 0, 0]}>
                        <group name="cube_25">
                          <mesh
                            name="Object_47"
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_47.geometry}
                            material={materials.material_0}
                          />
                        </group>
                        <group name="FingerBone1_27" position={[-0.188, 0.063, 0]}>
                          <group name="cube_26">
                            <mesh
                              name="Object_50"
                              castShadow
                              receiveShadow
                              geometry={nodes.Object_50.geometry}
                              material={materials.material_0}
                            />
                          </group>
                        </group>
                        <group name="ThumbBone1_29" position={[-0.203, -0.063, 0]}>
                          <group name="cube_28" position={[0.016, 0, 0]}>
                            <mesh
                              name="Object_53"
                              castShadow
                              receiveShadow
                              geometry={nodes.Object_53.geometry}
                              material={materials.material_0}
                            />
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                  <group name="Arm2_42" position={[0.188, 0.469, 0]}>
                    <group name="cube_33">
                      <mesh
                        name="Object_56"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_56.geometry}
                        material={materials.material_0}
                      />
                    </group>
                    <group name="LowerArm2_41" position={[0.313, 0.031, -0.031]}>
                      <group name="cube_34" position={[-0.313, -0.031, 0.031]}>
                        <mesh
                          name="Object_59"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_59.geometry}
                          material={materials.material_0}
                        />
                      </group>
                      <group name="Hand2_40" position={[0.313, 0, 0]}>
                        <group name="cube_35">
                          <mesh
                            name="Object_62"
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_62.geometry}
                            material={materials.material_0}
                          />
                        </group>
                        <group name="FingerBone2_37" position={[0.188, 0.063, 0]}>
                          <group name="cube_36">
                            <mesh
                              name="Object_65"
                              castShadow
                              receiveShadow
                              geometry={nodes.Object_65.geometry}
                              material={materials.material_0}
                            />
                          </group>
                        </group>
                        <group name="ThumbBone2_39" position={[0.203, -0.063, 0]}>
                          <group name="cube_38" position={[-0.016, 0, 0]}>
                            <mesh
                              name="Object_68"
                              castShadow
                              receiveShadow
                              geometry={nodes.Object_68.geometry}
                              material={materials.material_0}
                            />
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                  <group name="Torso_55">
                    <group name="Leg1_48" position={[-0.109, 0, 0]}>
                      <group name="cube_43" position={[-0.016, 0, 0]}>
                        <mesh
                          name="Object_72"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_72.geometry}
                          material={materials.material_0}
                        />
                      </group>
                      <group name="LowerLeg1_47" position={[0.016, -0.5, 0]}>
                        <group name="cube_44" position={[-0.031, 0.5, 0]}>
                          <mesh
                            name="Object_75"
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_75.geometry}
                            material={materials.material_0}
                          />
                        </group>
                        <group name="Foot_46" position={[-0.031, -0.438, 0]}>
                          <group name="cube_45" position={[0, 0.938, 0]}>
                            <mesh
                              name="Object_78"
                              castShadow
                              receiveShadow
                              geometry={nodes.Object_78.geometry}
                              material={materials.material_0}
                            />
                          </group>
                        </group>
                      </group>
                    </group>
                    <group name="Leg2_54" position={[0.109, 0, 0]}>
                      <group name="cube_49" position={[0.016, 0, 0]}>
                        <mesh
                          name="Object_81"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_81.geometry}
                          material={materials.material_0}
                        />
                      </group>
                      <group name="LowerLeg2_53" position={[-0.016, -0.5, 0]}>
                        <group name="cube_50" position={[0.031, 0.5, 0]}>
                          <mesh
                            name="Object_84"
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_84.geometry}
                            material={materials.material_0}
                          />
                        </group>
                        <group name="Foot2_52" position={[0.031, -0.438, 0]}>
                          <group name="cube_51" position={[0, 0.938, 0]}>
                            <mesh
                              name="Object_87"
                              castShadow
                              receiveShadow
                              geometry={nodes.Object_87.geometry}
                              material={materials.material_0}
                            />
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/sonic_oc_character_base.glb')

export default Sonic;