/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

 const Truck=(props)=> {
  const { nodes, materials } = useGLTF('/truck_final.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder035.geometry}
        material={materials['Material.266']}
        position={[-0.388, -1.115, 2.347]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.555, 0.037, 0.555]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube198.geometry}
        material={materials['Material.275']}
        position={[-1.394, 0.224, 0.371]}
        rotation={[0, 0, -Math.PI]}
        scale={[-0.089, -1.179, -0.088]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube184.geometry}
          material={materials['Material.286']}
          position={[0, 0, -21.576]}
          scale={[0.787, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube185.geometry}
          material={materials['Material.284']}
          position={[-39.236, 0, -21.576]}
          scale={[0.52, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube186.geometry}
          material={materials['Material.283']}
          position={[-35.07, 0, -21.576]}
          scale={[0.546, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube187.geometry}
          material={materials['Material.277']}
          position={[-6.164, 0, -21.576]}
          scale={[0.823, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube188.geometry}
          material={materials['Material.278']}
          position={[-11.416, 0, -21.576]}
          scale={[0.772, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube189.geometry}
          material={materials['Material.282']}
          position={[-30.639, 0, -21.576]}
          scale={[0.653, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube190.geometry}
          material={materials['Material.281']}
          position={[-26.018, 0, -21.576]}
          scale={[0.641, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube191.geometry}
          material={materials['Material.280']}
          position={[-21.59, 0, -21.576]}
          scale={[0.729, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube192.geometry}
          material={materials['Material.276']}
          position={[-42.746, 0, -11.508]}
          scale={[1.296, 1, 0.527]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube193.geometry}
          material={materials['Material.273']}
          position={[-4.729, 0, 0]}
          scale={[0.968, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube194.geometry}
          material={materials['Material.272']}
          position={[-9.774, 0, 0]}
          scale={[0.864, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube195.geometry}
          material={materials['Material.271']}
          position={[-14.582, 0, 0]}
          scale={[0.909, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube196.geometry}
          material={materials['Material.285']}
          position={[-42.342, -0.916, -11.052]}
          rotation={[-Math.PI, 0, 0]}
          scale={[-1.92, -0.091, -12.689]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube197.geometry}
          material={materials['Material.279']}
          position={[-15.862, 0, -21.576]}
          scale={[0.614, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube199.geometry}
          material={materials['Material.274']}
          position={[-39.236, 0, 0]}
          scale={[0.973, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube200.geometry}
          material={materials['Material.267']}
          position={[-35.505, 0, 0]}
          scale={[1.009, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube201.geometry}
          material={materials['Material.269']}
          position={[-24.579, 0, 0]}
          scale={[1.009, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube202.geometry}
          material={materials['Material.270']}
          position={[-19.542, 0, 0]}
          scale={[0.848, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube203.geometry}
          material={materials['Material.268']}
          position={[-29.972, 0, -0.235]}
          scale={[1.009, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube204.geometry}
          material={materials['Material.287']}
          position={[-18.885, 0.008, -10.893]}
          scale={[24.446, 1.075, 11.349]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube205.geometry}
          material={materials['Material.265']}
          position={[26.067, -0.89, -11.052]}
          rotation={[-Math.PI, 0, 0]}
          scale={[-1.92, -0.091, -12.689]}
        />
        <group
          position={[15.579, -0.19, -10.893]}
          rotation={[0, 0, -Math.PI]}
          scale={[-11.174, -0.848, -11.349]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube206_2.geometry}
            material={materials['Material.288']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube206_3.geometry}
            material={materials['Material.260']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube206_4.geometry}
            material={materials['Material.259']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube206_5.geometry}
            material={materials['Material.258']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube206_6.geometry}
            material={materials['Material.257']}
          />
        </group>
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder034.geometry}
        material={materials['Material.264']}
        position={[-0.388, -1.115, 0.326]}
        rotation={[-1.64, -0.908, 3.058]}
        scale={[-0.555, -0.037, -0.555]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder033.geometry}
        material={materials['Material.262']}
        position={[-4.308, -1.115, 2.347]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.555, 0.037, 0.555]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder032.geometry}
        material={materials['Material.263']}
        position={[-4.276, -1.115, 0.326]}
        rotation={[-1.64, -0.908, 3.058]}
        scale={[-0.555, -0.037, -0.555]}
      />
    </group>
  )
}

useGLTF.preload('/truck_final.glb')


export default Truck;